node_config: 
    nproc: 1
    # controls whether to use MPI or not in docker or WSL
    prohibit_mpi: False

    # manually set whether mpi is available or not
    mpi_available: False

    # for node_hint==docker/docker_mpi
    image: null 

    # for node_hint==wsl/wsl_mpi
    distro: null  # linux distro name of one's wsl installation
    user: null      # user name of one's wsl installation
    rosetta_bin: null # the real path of rosetta binary inside wsl
