# This is the configuration of REvoDesign program.
# A copy of `REvoDesign/config/revodesign/global_config.yaml` will be created inside `$HOME/.REvoDesign/config/` 
# to perform customized configurations while REvoDesign is called at the very first time.
# Click menu-REvoDesign-Reconfigure to apply changes from this copy. 

ui:
  header_panel: 
    input: 
      molecule: ''
      chain_id: ''
    cmap: 
      default: bwr_r
    nproc: 6
  # footer_panel: 
  #   progressbar:
  prepare:
    input:
      pocket:
        substrate: ''
        cofactor: ''
        to_pse: ''
        
      surface: 
        to_pse: ''
        exclusion: ''

    ligand_radius: 8.0
    cofactor_radius: 7.0
    chain_dist: 3.0
    surface_probe_radius: 15.0


  mutate:
    input:
      profile: ''
      profile_type: PSSM
      residue_ids: ''
      to_pse: ''
      design_case: default
    min_score: -2
    max_score: 10
    reject: PC
    accept: E:DATY K:RATY N:ATY Q:EDATY
    reverse_score: False
    designer:
      temperature: 0.1
      batch: 10
      num_sample: 1
      enable_randomized_sampling: False
      randomized_sampling: 3
      deduplicate_designs: True
      homooligomeric: False

  evaluate:
    input:
      to_mutant_txt: ''
    rock: False
    show_wt: True
    reverse_score: False

  cluster:
    input:
      from_mutant_txt: ''
    mut_num_min: 1
    mut_num_max: 1
    num_cluster: 15
    score_matrix: 
      group:
      default: PAM30
    batch_size: 100
    shuffle: True
    
  
  visualize:
    input:
      from_mutant_txt: ''
      to_pse: ''
      profile: ''
      profile_type: PSSM
      group_name: default
      best_leaf: ''
      totalscore: ''

      multi_design:
        to_mutant_txt: ''
    
    global_score_policy: True
    reverse_score: False
    multi_design:
      num_mut_max: 5
      num_variant_max: 20
      spatial_dist: 30.0
      use_bond_CA: True
      use_sidechain_orientation: True
      use_external_scorer: True
      color_by_scores: True
    full_pdb: False


  interact:
    input:
      gremlin_pkl: ''
      to_mutant_txt: ''

    topN_pairs: 100
    max_interact_dist: 20.0
    interact_ignore_wt: False
    use_external_scorer: 
    reverse_score: False
  
  client:
    pssm_gremlin_url: https://revodesign.yaoyy.moe/
    pssm_gremlin_user: revodesign_users
    pssm_gremlin_passwd: 1234567
  
  socket: 
    input:
      key: ''
      hostname: ''

    server_mode: False
    server_url: localhost
    server_port: 63189
    use_key: True

    broadcast:
      interval: 0.001
      mutagenesis: True
      view: False


    receive:
      mutagenesis: True
      view: False



  config: 
    sidechain_solver:
      group:
        - Dunbrack Rotamer Library
        - DLPacker
        - PIPPack
      default: DLPacker

      model: 
      repack_radius: 0.0

      pippack:
        model_names:
          group:
            - pippack_model_1
            - pippack_model_2
            - pippack_model_3
            - ensemble
          default: ensemble

profile:
  group:
    - PSSM
    - CSV
    - TSV
    - Pythia-ddG
designer:
  group:
    - 
    - ProteinMPNN


log:
  version: 1
  disable_existing_loggers: true
  formatters:
    simple:
      format: '%(message)s'
      datefmt: '%Y-%m-%dT%H:%M:%S%z'
    json:
      fmt_keys:
        level: levelname
        message: message
        timestamp: timestamp
        logger: name
        module: module
        function: funcName
        line: lineno
        thread_name: threadName
  handlers:
    stdout:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
    stderr:
      class: logging.StreamHandler
      level: ERROR
      formatter: simple
      stream: ext://sys.stderr
    file:
      class: logging.handlers.RotatingFileHandler
      level: NOTSET
      formatter: json
      filename: logs/revodesign.log.jsonl
      maxBytes: 1000_000
      backupCount: 3
    notebook:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: json
      filename: logs/revodesign.notebook.jsonl
      maxBytes: 1000_000
      backupCount: 30

  loggers:
    root:
      level: NOTSET


cache_dir:
  # ~/.REvoDesign/
  under_home_dir: True
  customized: 