version: 2.1

# Define reusable executor with Miniconda setup
executors:
  conda-executor:
    docker:
      - image: continuumio/miniconda3:latest
    environment:
      DISPLAY: ':99.0'  # Added environment variable
      PATH: "/opt/conda/bin:$PATH"

# Define reusable commands
commands:
  setup-miniconda:
    parameters:
      python_version:
        type: string
    steps:
      - run:
          name: Set up Miniconda
          command: |
            conda update -n base -c defaults conda -y
            conda create -n test-env python<<parameters.python_version>> -y
            echo "source activate test-env" >> ~/.bashrc
            source activate test-env

  run-make-tasks:
    steps:
      - run:
          name: Run Makefile Commands
          command: |
            make setup-display
            conda install -c conda-forge pymol-open-source -y
            make install
            make prepare-test
            make all-test

# Main workflows
jobs:
  test-python:
    executor: conda-executor
    parameters:
      python_version:
        type: string
    steps:
      - checkout
      - setup-miniconda:
          python_version: <<parameters.python_version>>
      - run-make-tasks

workflows:
  version: 2
  test-matrix:
    jobs:
      - test-python:
          python_version: "3.9"
      - test-python:
          python_version: "3.10"
      - test-python:
          python_version: "3.11"
      - test-python:
          python_version: "3.12"
