version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    parameters:
      python-version:
        type: string
        default: "3.9"
    docker:
      - image: yaoyinying/revodesign-test-image:py<< parameters.python-version >>-cpu-only
    environment:
      DISPLAY: ':99.0'
    steps:
      - checkout
      
      - run:
          name: Start Display
          command: |
            make setup-display

      - run:
          name: Setup Environment for << parameters.python-version >>
          command: |
            source activate REvoDesign

      - run:
          name: Install REvoDesign
          command: |
            source activate REvoDesign
            make install

      - run:
          name: Run Unit Tests
          command: |
            source activate REvoDesign
            make all-test

      - run:
          name: Generate Coverage Report
          command: |
            source activate REvoDesign
            coverage xml

      - codecov/upload:
          file: coverage.xml

workflows:
  version: 2
  test:
    jobs:
      - build-and-test:
          matrix:
            parameters:
              python-version: ["3.9", "3.10", "3.11"]
