version: 2.1

orbs:
  codecov: codecov/codecov@5.2.1

jobs:
  build-and-test:
    parameters:
      python-version:
        type: string
        default: "3.9"
    docker:
      - image: continuumio/miniconda3
    environment:
      DISPLAY: ':99.0'
    steps:
      - checkout
      
      - run:
          name: Apt installs
          command: |
            apt-get update
            apt-get install -y build-essential make sudo xvfb fluxbox curl

      - run:
          name: Start Display
          command: |
            make setup-ubuntu

      - run:
          name: Setup Environment for << parameters.python-version >>
          command: |
            conda create --name REvoDesign python=<< parameters.python-version >> -y
            source activate REvoDesign
            conda install << parameters.conda-channel >> << parameters.pymol-version >> -y

      - run:
          name: Install REvoDesign
          command: |
            source activate REvoDesign
            make install


      - run:
          name: Run Tests against << parameters.pymol-tag >>
          command: |
            source activate REvoDesign
            make prepare-test
            make all-test

      - run:
          name: Generate Coverage Report
          command: |
            source activate REvoDesign
            coverage xml

      - codecov/upload

workflows:
  version: 2
  test:
    jobs:
      - build-and-test:
          python-version: "3.9" # https://pymol.org/
          pymol-tag: 'legacy python with pymol 3.0'
          pymol-version: "pymol-open-source<3.1 pyqt=5.15 qt-main=5" 
          conda-channel: -c conda-forge

      - build-and-test:
          python-version: "3.12" # https://pymol.org/
          pymol-tag: 'latest pymol open source'
          pymol-version: "pymol-open-source"
          conda-channel: -c conda-forge

      - build-and-test:
          python-version: "3.10" # https://pymol.org/
          pymol-tag: 'latest pymol bundle'
          pymol-version: "pymol-bundle"
          conda-channel: -c schrodinger -c conda-forge

      - build-and-test:
          python-version: "3.11"
          pymol-tag: 'legacy (v2) pymol open source'
          pymol-version: "pymol-open-source<3"
          conda-channel: -c conda-forge

      - build-and-test:
          python-version: "3.11" # https://storage.googleapis.com/pymol-storage/installers/index.html https://anaconda.org/schrodinger/pymol-bundle/files
          pymol-tag: 'legacy (v2) pymol bundle'
          pymol-version: "pymol-bundle<3"
          conda-channel: -c schrodinger -c conda-forge
          
