'''
Magic numbers in enzyme design.

'''

# Determine
DEFAULT_SURFACE_PROBE_RADIUS = 15
DEFAULT_SUBSTRATE_POCKET_RADIUS = 6
DEFAULT_COFACTOR_POCKET_RADIUS = 7
DEFAULT_INTERCHAIN_RADIUS = 3


# Cluster

DEFAULT_CLUSTER_NUM = 15
DEFAULT_CLUSTER_RANGE = [x for x in range(2, 31, 2)]
DEFAULT_CLUSTER_MIN_MUT = 1
DEFAULT_CLUSTER_MAX_MUT = 1
DEFAULT_CLUSTER_BATCH_SIZE = 1000

DEFAULT_CLUSTER_SCORE_MTX = 'PAM30'


DEFAULT_GREMLIN_TOPN_NUM = 50
DEFAULT_GREMLIN_SPATIAL_MAX_DIST = 30

DEFAULT_PROFILE_TYPE_GROUP = ['PSSM', 'CSV', 'TSV']  # default profile type
DEFAULT_PROFILE_TYPE = 'PSSM'
