mounts:
  - host_path: "/mnt/db/weights/alphafold"
    container_path: "/root/.cache/colabfold"
    mode: "ro"
env: {}
gpus: true
nproc: 1
max_runtime_seconds: 7200
defaults: {}
# slurm_image: /mnt/data/srv/revodesign/server-slurm/images/bioemu_v1.sif
