mounts:
  - host_path: "/mnt/db/weights/easifa2"
    container_path: "/mnt/db/weights/easifa2"
    mode: "ro"
  - host_path: "/mnt/db/weights/esm"
    container_path: "/mnt/db/weights/esm"
    mode: "ro"
env:
  TORCH_HOME: "/mnt/db/weights/esm"
max_runtime_seconds: 3600
defaults: {}
