mounts:
  - host_path: "/mnt/db/weights/easifa"
    container_path: "/mnt/db/weights/easifa"
    mode: "ro"
env: {}
gpus: true
nproc: 1
max_runtime_seconds: 3600
defaults: {}
# slurm_image: /mnt/data/srv/revodesign/server-slurm/images/easifa_v1.sif
