# RFdiffusion runner — local development settings.
mounts:
  - host_path: "/mnt/db/weights/RFdiffusion/models"
    container_path: "/opt/RFdiffusion/models"
    mode: "ro"
env: {}
gpus: true
nproc: 1
max_runtime_seconds: 14400
defaults: {}
# slurm_image: /mnt/data/srv/revodesign/server-slurm/images/placer-rfdiffusion_v1.sif
