# register all variables here
# TODO: dynamic variables loading and saving
# TODO: load preset variables on bootstrap
variables:
  # ROSETTA_BIN: /Users/yyy/rosetta/rosetta_binary/rosetta.source.release-371/main/source/bin/
