# This is the configuration of REvoDesign program.
# A copy of `src/REvoDesign/config/revodesign/global_config.yaml` will be created inside `<user_data_dir>/REvoDesign/config/` 
# to perform customized configurations while REvoDesign is called at the very first time.
# Click menu-File-Reconfigure to apply changes from this copy. 

language: eng-eng
work_dir: '.'

ui:
  header_panel: 
    input: # TODO: move to a separate config file `runtime`
      molecule: ''
      chain_id: ''
    cmap: 
      default: bwr_r
      reverse_score: False
    nproc: 6
  
  
  prepare:
    input:
      pocket:
        substrate: ''
        cofactor: ''
        to_pse: ''
        
      surface: 
        to_pse: ''
        exclusion: ''

    ligand_radius: 8.0
    cofactor_radius: 7.0
    chain_dist: 3.0
    surface_probe_radius: 15.0


  mutate:
    input:
      profile: ''
      profile_type: PSSM
      residue_ids: ''
      to_pse: ''
      design_case: default
    min_score: -2
    max_score: 10
    reject: 'PC'
    accept: E:DATY K:RATY N:ATY Q:EDATY
    designer:
      temperature: 0.1
      batch: 10
      num_sample: 1
      enable_randomized_sampling: False
      randomized_sampling: 3
      deduplicate_designs: True
      homooligomeric: False

  evaluate:
    input:
      to_mutant_txt: ''
    show_wt: True

  cluster:
    input:
      from_mutant_txt: ''
    mut_num_min: 1
    mut_num_max: 1
    num_cluster: 15
    score_matrix: 
      default: PAM30
    batch_size: 100
    shuffle: True
    mutate_relax: False
    
  
  visualize:
    input:
      from_mutant_txt: ''
      to_pse: ''
      profile: ''
      profile_type: PSSM
      group_name: default
      best_leaf: ''
      totalscore: ''

      multi_design:
        to_mutant_txt: ''
    
    global_score_policy: True
    multi_design:
      num_mut_max: 5
      num_variant_max: 20
      spatial_dist: 30.0
      use_bond_CA: True
      use_sidechain_orientation: True
      use_external_scorer: True
      color_by_scores: True
    full_pdb: False


  interact:
    input:
      gremlin_pkl: ''
      to_mutant_txt: ''

    topN_pairs: 100
    max_interact_dist: 20.0
    interact_ignore_wt: False
    use_external_scorer: ''
    chain_binding: 
      enabled: False
      chains_to_bind: "ABCD"
  
  
  socket: 
    input:
      key: 

    server_mode: False
    server_url: localhost
    server_port: 63189
    use_key: True

    broadcast:
      interval: 0.001
      mutagenesis: True
      view: False

    receive:
      mutagenesis: True
      view: False

  config: 
    sidechain_solver:
      use: "Dunbrack Rotamer Library"
      model: '' # TODO: deprecated
      repack_radius: 0.0 # TODO: deprecated

editor:
  backend:
    host: '127.0.0.1'
    port: 5000
    use_ssl: False
    no_token: False
    crt: 
    key:
    html_dir: 
  token:

# for deep learning frameworks like pytorch, tensorflow, etc.
# unified device setting across all deep learning frameworks
accelerator: cpu

# TODO: config setting triggers
config_settings:
  auto_save: False
  save_on_exit: False
  save_interval: 100 # in seconds

rosetta: 
  node_hint: native # Literal["docker", "docker_mpi", "mpi", "wsl", "wsl_mpi", "native"]

  opts: 
    general: -ignore_unrecognized_res # -extra_res_fa XXX
    extra_res: # TODO: window pop

  cart_ddg:
    use_legacy: False
    relax:
      nstruct: 4
    iterations: 3

# TODO: move to a separate config file `openmm`
openmmsetup:
  host: '127.0.0.1'
  port: 5050


# register all variables here
# TODO: dynamic variables loading and saving
# TODO: load preset variables on bootstrap
# TODO: move to a separate config file `environ`
environment:
  variables:
    # ROSETTA_BIN: /Users/yyy/rosetta/rosetta_binary/rosetta.source.release-371/main/source/bin/

# TODO: move to a separate config file `logger`
log:
  version: 1
  disable_existing_loggers: true
  formatters:
    simple:
      format: '%(message)s'
      datefmt: '%Y-%m-%dT%H:%M:%S%z'
    json:
      fmt_keys:
        level: levelname
        message: message
        timestamp: timestamp
        logger: name
        module: module
        function: funcName
        line: lineno
        thread_name: threadName
  handlers:
    stdout:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
    stderr:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stderr
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: json
      filename: AUTO
      maxBytes: 1000_000
      backupCount: 10
    notebook:
      class: logging.handlers.RotatingFileHandler
      level: WARNING
      formatter: json
      filename: AUTO
      maxBytes: 1000_000
      backupCount: 30

  loggers:
    root:
      level: DEBUG


cache_dir:
  # ~/.REvoDesign/
  under_home_dir: True
  customized: 

# TODO: move to a separate config file `runtime`
designable_sequences: 