class REvoDesignWarning(Warning):
class PerformanceWarning(REvoDesignWarning):
class REvoDesignSessionsWarning(REvoDesignWarning):
class CoevolveAnalysisWarning(REvoDesignWarning):
class BadDataWarning(REvoDesignWarning):
class NoResultsWarning(REvoDesignWarning):
class REvoDesignWidgetWarning(REvoDesignWarning):
class AlreadyDisconnectedWarning(REvoDesignWidgetWarning):
class DisabledFunctionWarning(REvoDesignWarning):
class ConflictWarning(RuntimeWarning):
class NoInputWarning(REvoDesignWarning):
class EmptySessionWarning(REvoDesignWarning):
class InvalidSessionWarning(REvoDesignWarning):
class FallingBackWarning(REvoDesignWarning):
class CrystalStructureWarning(REvoDesignWarning):
class ResidueMissingWarning(CrystalStructureWarning):
class OverridesWarning(REvoDesignWarning):
class PlatformNotSupportedWarning(RuntimeWarning):
class AppleSiliconRosetta2Warning(PlatformNotSupportedWarning):
class CIRunnerWarning(PlatformNotSupportedWarning):
class MoleculeWarning(NoInputWarning):
class SocketWarning(REvoDesignWarning):
class SocketUserAlreadyExists(SocketWarning):
class SocketMessageOverflow(SocketWarning):
class SocketMeetingRoomIsEmpty(SocketWarning):
class MissingExternalTool(REvoDesignWarning):
    """Warning raised when a external tool is missing"""