name: Docker Image for Server

on:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set environment variable with current date
      run: |
        echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
        echo "DATE: ${{ env.DATE }}"
    
    - name: Build runner Docker image
      run: docker build -f server/docker/runner/Dockerfile . -t revodesign-pssm-gremlin-non-root

    - name: Build server Docker image
      run: docker build -f server/docker/server/Dockerfile . -t revodesign-pssm-gremlin-server-non-root

    - name: Tag Docker image with date and latest
      run: |
        docker tag revodesign-pssm-gremlin-non-root yaoyinying/revodesign-pssm-gremlin-non-root:${{ env.DATE }}
        docker tag revodesign-pssm-gremlin-non-root yaoyinying/revodesign-pssm-gremlin-non-root:latest
        docker tag revodesign-pssm-gremlin-server-non-root yaoyinying/revodesign-pssm-gremlin-server:${{ env.DATE }}
        docker tag revodesign-pssm-gremlin-server-non-root yaoyinying/revodesign-pssm-gremlin-server-non-root:latest

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_GITHUB_REPO_SECRET }}" | docker login -u yaoyinying --password-stdin

        
    - name: Push Docker image
      run: |
        docker push yaoyinying/revodesign-pssm-gremlin-non-root:${{ env.DATE }}
        docker push yaoyinying/revodesign-pssm-gremlin-non-root:latest
        docker push yaoyinying/revodesign-pssm-gremlin-server-non-root:${{ env.DATE }}
        docker push yaoyinying/revodesign-pssm-gremlin-server-non-root:latest

    - name: Refresh Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: yaoyinying
        password: ${{ secrets.DOCKER_GITHUB_REPO_SECRET }}
        repository: yaoyinying/revodesign-pssm-gremlin-non-root
        readme-filepath: ./server/README.md
        enable-url-completion: true
