name: Test REvoDesign

on:
  push:
    paths:
      - '.github/workflows/unit_tests.yml' # monitor the main workflow script.
      - 'tests/*.py' # monitor the unit tests
      - 'REvoDesign' # monitor the REvoDesign project source code
      
    branches:
      - main

env: 
  conda_env: REvoDesign


jobs:
  REvoDesign-UnitTests:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set environment variable with current repo dir
        run: |
          echo "REPO=$PWD" >> $GITHUB_ENV
        
      
      - name: Setup Conda on ${{ matrix.os }}
        uses: conda-incubator/setup-miniconda@v3
        with:
            auto-update-conda: true
            activate-environment: ${{ env.conda_env }}

      - name: Setup PyMOL on ${{ matrix.os }}
        run: |
          conda install -c conda-forge pymol-open-source python -n ${{ env.conda_env }}-y 
          conda info
          conda list
          which python
          which python3
          ls ${{env.CONDA}}/${{ env.conda_env }} || echo never mind.


      - name: Install REvoDesign on ${{ matrix.os }}
        run: |
          which python
          which python3
          ${{env.CONDA}}/${{ env.conda_env }}/python -m pip install .[colabdesign] -U

      - name: Unit Test on ${{ matrix.os }}
        env:
          REVODESIGN_USERS: ${{ secrets.REVODESIGN_USERS }}
          REVODESIGN_SERVER_PASS: ${{ secrets.REVODESIGN_SERVER_PASS }}

        run: |
          ${{env.CONDA}}/${{ env.conda_env }}/python ${{ env.REPO }}/tests/UnitTests.py
