name: Test REvoDesign

on:
  push:
    paths:
      - '.github/workflows/unit_tests.yml' # monitor the main workflow script.
      - 'tests/*.py' # monitor the unit tests
      - 'REvoDesign' # monitor the REvoDesign project source code

      
    branches:
      - main


env:
  incensive_pymol_version: 2.5.7
  incensive_pymol_base_url: https://storage.googleapis.com/pymol-storage/installers
  
  
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    env:
      PYTHON_EXEC: ${{ matrix.os != 'windows-latest'  && 'python3' || 'C:\Programs\PyMOL\python.exe' }} 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        if: ${{ matrix.os != 'windows-latest' }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        

      - name: Setup PyMOL for Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }} 
        run: >
          sudo apt-get update;
          sudo apt-get --no-install-recommends install pymol

      
      - name: Setup PyMOL for MacOS
        if: ${{ matrix.os == 'macOS-latest' }}
        run: >
          brew install pymol

      - name: Setup PyMOL for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          incensive_pymol_installer_basename: PyMOL-${{ env.incensive_pymol_version }}-Windows-x86_64.exe
        run: |
            curl.exe -O ${{ env.incensive_pymol_base_url }}/${{ env.incensive_pymol_installer_basename }}
            start /wait "" ${{ env.incensive_pymol_installer_basename }} /InstallationType=AllUsers /S /D=C:\Programs\PyMOL

      - name: Install REvoDesign
        run: |
          ${{ env.PYTHON_EXEC }} -m pip install .[colabdesign] -U

      - name: Unit Test
        env:
          REVODESIGN_USERS: ${{ secrets.REVODESIGN_USERS }}
          REVODESIGN_SERVER_PASS: ${{ secrets.REVODESIGN_SERVER_PASS }}
          REPO: ${{ github.repository }}
        run: |
          ${{ env.PYTHON_EXEC }} ${{ env.REPO }}/tests/UnitTests.py
