name: Unit Test in docker

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Test image tags'
        required: true
        type: string
        default: 'latest'
      useSelfHostedRunnerOnly:
        description: 'Use self-hosted runners only'
        required: false
        type: boolean
        default: false
  push:
    paths:
      - '.github/workflows/unit_tests_dev.yml' # monitor the main workflow script.
      - 'tests/*.py' # monitor the unit tests
      - 'REvoDesign/*' # monitor the REvoDesign project source code
      - '!CHANGELOG.md' 
      - '!REvoDesign/__version__.py'
    branches:
        - main

jobs:
  DevTests:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ${{ 'ubuntu-latest' && ! inputs.useSelfHostedRunnerOnly || 'ubuntu-japs' }}
        python-version: 
          - "3.9"
          - "3.10"
          - "3.11"

    runs-on: ${{ matrix.os }}

    container: 
      image: yaoyinying/revodesign-test-image:py${{ matrix.python-version }}-${{ inputs.imageTag || 'latest' }}

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      DISPLAY: ':99.0'


    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setting up display
      # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
      # https://github.com/tlambert03/setup-qt-libs
      - name: setup Qt headless Display on Ubuntu
        run: |
          source activate REvoDesign
          make setup-display

      - name: Install REvoDesign on ${{ matrix.os }}
        run: |
          source activate REvoDesign
          make install-no-dept

      - name: Full Unit Test on Ubuntu
        env:
          REVODESIGN_USERS: ${{ secrets.REVODESIGN_USERS }}
          REVODESIGN_SERVER_PASS: ${{ secrets.REVODESIGN_SERVER_PASS }}

        run: |
          source activate REvoDesign
          make prepare-test
          conda info
          conda list
          make all-test
          make pymol-test
      
      - name: Convert coverage report to XML for codecov
        run: |
          source activate REvoDesign
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Clean up
        run: |
          make clean