name: Test REvoDesign

on:
  push:
    paths:
      - '.github/workflows/unit_tests.yml' # monitor the main workflow script.
      - 'tests/*.py' # monitor the unit tests
      - 'REvoDesign' # monitor the REvoDesign project source code
      
    branches:
      - main

env: 
  conda_env: REvoDesign


jobs:
  REvoDesign-UnitTests:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set environment variable with current repo dir
        run: |
          echo "REPO=$PWD" >> $GITHUB_ENV
        
      
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
            auto-update-conda: true
            miniconda-version: "latest"
            activate-environment: ${{ env.conda_env }}

      - name: Setup PyMOL
        run: |
          conda install -c conda-forge pymol-open-source -y


      - name: Install REvoDesign
        run: |
          python -m pip install .[colabdesign] -U

      - name: Unit Test
        env:
          REVODESIGN_USERS: ${{ secrets.REVODESIGN_USERS }}
          REVODESIGN_SERVER_PASS: ${{ secrets.REVODESIGN_SERVER_PASS }}

        run: |
          python ${{ env.REPO }}/tests/UnitTests.py
