name: Bare Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

env: 
  conda_env: REvoDesign
  ENABLE_ROSETTA_CONTAINER_NODE_TEST: "YES" # Github Actions: run python against container node

jobs:
  BareTests:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
        conda-channel:
          - -c conda-forge
        pymol-version:
          - "pymol-open-source<3.1"
        pymol-tag:
          - 'latest pymol open source'
        python-version: 
          # - "3.9"
          - "3.10"
          # - "3.11"
          - "3.12"
        include:
        # #   # windows
        # #   - os: windows-latest
        # #     python-version: "3.11"
        # #     conda-channel: -c conda-forge
        # #     pymol-version: "pymol-open-source"
        # #     pymol-tag: 'latest pymol open source'
          
          # latest bundled pymol 
          - os: ubuntu-latest
            python-version: "3.10"
            pymol-version: "pymol-bundle"
            pymol-tag: 'latest pymol bundle'
            conda-channel: -c schrodinger -c conda-forge
          
        #   # pymol-open-source, v2
        #   - os: ubuntu-latest
        #     python-version: "3.11"
        #     pymol-version: "pymol-open-source<3"
        #     conda-channel: -c conda-forge
        #     pymol-tag:
        #       - 'legacy (v2) pymol open source'

        #   # bundled pymol, v2
        #   - os: ubuntu-latest
        #     python-version: "3.10"
        #     pymol-version: "pymol-bundle<3"
        #     conda-channel: -c schrodinger -c conda-forge
        #     pymol-tag:
        #       - 'legacy (v2) pymol bundle'

    runs-on: ${{ matrix.os }}
    timeout-minutes: 35


    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      DISPLAY: ':99.0'

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: setup Qt headless Display on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          make setup-display-gha

      - name: Verify Docker Version and Pull Rosetta Image
        run: |
          docker --version
          docker pull --platform=linux/amd64 rosettacommons/rosetta:mpi

      - name: setup Qt headless Display on Windows
        if: startsWith(matrix.os, 'windows')
        uses: pyvista/setup-headless-display-action@v2
      
      - name: Setup Conda on ${{ matrix.os }} 
        uses: conda-incubator/setup-miniconda@v3
        with:
            auto-update-conda: false
            activate-environment: ${{ env.conda_env }}
            auto-activate-base: false
            python-version: ${{ matrix.python-version }}
            conda-solver: libmamba
      
      - name: Setup PyMOL - (${{ matrix.pymol-tag }})-(${{ matrix.os }}-py${{ matrix.python-version }})
        run: |
          conda install ${{ matrix.conda-channel}} '${{ matrix.pymol-version}}' pyqt=5 -n ${{ env.conda_env }} -y
          conda info
          conda list
          which python
          which python3
      - name: Install REvoDesign on ${{ matrix.os }}
        run: |
          make install
          make install-dgl-linux
          


      - name: Full Unit Test on Ubuntu
        run: |
          make prepare-test
          make all-test
      
      - name: Convert coverage report to XML for codecov
        run: |
          coverage xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Clean up
        run: |
          make clean