name: Unit Test in docker

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Test image tags'
        required: true
        type: string
        default: 'latest'
      useSelfHostedRunnerOnly:
        description: 'Use self-hosted runners only'
        required: false
        type: boolean
        default: false
  push:
    paths:
      - '.github/workflows/unit_tests_dev.yml' # monitor the main workflow script.
      - 'tests/*.py' # monitor the unit tests
      - 'REvoDesign/*' # monitor the REvoDesign project source code
      - '!CHANGELOG.md' 
      - '!REvoDesign/__version__.py'
    branches:
        - main
        - linting-4

env:
  lint-python-version: '3.11'        

jobs:
  DevTests:
    strategy:
      fail-fast: false
      matrix:
        os: 
          # if any:
          # - workflow_dispatch requires self-hosted runners 
          # - commit message does NOT contain 'fast-test', use japs runner. 
          # otherwise:
          # - use github-hosted runners
          - 'ubuntu-latest'
        python-version: 
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    runs-on: ${{ matrix.os }}
  
    outputs:
      linted: ${{steps.skip-lint.outputs.linted }}
      lint-svg-url: ${{ steps.pylint-scanning.outputs.svg_link}}
      lint-markdown: ${{ steps.pylint-scanning.outputs.markdown_text}}
      lint-svg-path: ${{ steps.pylint-scanning.outputs.expected_badge_file}}

    container: 
      image: yaoyinying/revodesign-test-image:py${{ matrix.python-version }}-${{ inputs.imageTag || '2024-04-29' }}

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      DISPLAY: ':99.0'


    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setting up display
      # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
      # https://github.com/tlambert03/setup-qt-libs
      - name: setup Qt headless Display on Ubuntu
        run: |
          source activate REvoDesign
          make setup-display

      - name: Install REvoDesign on ${{ matrix.os }}
        run: |
          source activate REvoDesign
          make install-no-dept

      - name: Full Unit Test on Ubuntu
        env:
          REVODESIGN_USERS: ${{ secrets.REVODESIGN_USERS }}
          REVODESIGN_SERVER_PASS: ${{ secrets.REVODESIGN_SERVER_PASS }}

        run: |
          source activate REvoDesign
          make prepare-test
          conda info
          conda list
          make all-test
          make pymol-test
      
      - name: Convert coverage report to XML for codecov
        run: |
          source activate REvoDesign
          coverage xml

      - name: Skipped linting
        id: skip-lint
        run: |
          if [[ ${{matrix.python-version}} == ${{env.lint-python-version}} ]];then
            echo linted=1 >> $GITHUB_OUTPUT
          else
            echo linted=0 >> $GITHUB_OUTPUT
          fi

      - name: PyLint Scanning
        id: pylint-scanning
        if: steps.skip-lint.outputs.linted == 1
        
        uses: YaoYinYing/pylint-github-action@e60661e765cda461263a36599659cac38e3144ff
        with:
          lint-path: REvoDesign  # lint src package
          python-version: ${{ env.lint-python-version }}  # python version which will lint the package
          badge-text: pylint score
          badge-branch: badge
          badge-file-name: pylint_scan
          conda-env-name: REvoDesign
      
      - name: PyLint Badge Fetching
        id: pylint-badge-fetch
        if: steps.skip-lint.outputs.linted == 1
        run: |
          mkdir -p ./badge_dir_with_uniq_name
          curl -o ./badge_dir_with_uniq_name/${{ steps.pylint-scanning.outputs.expected_badge_file }} ${{ steps.pylint-scanning.outputs.svg_link }}
          
      - name: PyLint Badge Uploading
        if: steps.skip-lint.outputs.linted == 1
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: badge_dir_with_uniq_name
          destination-dir: ./badge_dir_with_uniq_name/REvoDesign/pylint/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Clean up
        run: |
          make clean